// Feature: json-viewer-free, Property 14: Validator reports the first error at the correct 1-based position
//
// Validates: Requirements 6.4
//
// "IF the Editor content contains one or more syntax errors, THEN THE Validator
//  SHALL display, for the first error encountered in reading order, an error
//  description identifying the error type together with the 1-based line number
//  and 1-based column number of the error location."
//
// Strategy
// --------
// Start from a *valid* JSON document (generated by `jsonArbitrary`), render it
// to text (compact `serialize` and multi-line `format` at every indentation
// style, so line/column computation is genuinely exercised), then inject a
// single illegal character ('#', which is invalid anywhere in JSON) at a known
// offset. Because the entire prefix up to the injection point is still valid,
// the parser's *first* error in reading order is exactly that injected
// character, so the 1-based line/column of the offset is the oracle we assert
// against.
//
// To keep the oracle exact, injection offsets are restricted to *token
// boundaries* outside string literals:
//   - never inside a string literal (a '#' there is legal JSON, no error), and
//   - never immediately after a value-token character (digit/letter/sign/'.'/'e'),
//     because splitting a number or keyword (e.g. `1.5e-7` -> `1.5e#-7`,
//     `true` -> `tr#ue`) makes the scanner report the *partial token*'s start
//     rather than the injected character.
// Offset 0 is always a valid boundary (the '#' is the very first character), so
// every document has at least one injection site.

import { describe, expect, it } from 'vitest';
import { fc, test } from '@fast-check/vitest';
import { parseJson } from './parse';
import { format, serialize, type IndentStyle } from './serialize';
import { jsonArbitrary } from '../../test/arbitraries';

// ─── Oracle helpers ──────────────────────────────────────────────────────────

/** The illegal character injected to create a single syntax error. */
const INJECTED = '#';

/**
 * Characters that can be part of a JSON *value token* (number or
 * `true`/`false`/`null`). Injecting immediately after one of these would split
 * the token and move the reported error to the token's start, so such offsets
 * are excluded from the injection sites.
 */
const VALUE_TOKEN_CHAR = /[0-9A-Za-z+\-.]/;

/** Convert a 0-based offset into a 1-based {line, column} (mirrors parse.ts). */
function lineColumn(text: string, offset: number): { line: number; column: number } {
  let line = 1;
  let lineStart = 0;
  for (let i = 0; i < offset; i++) {
    if (text.charCodeAt(i) === 10 /* \n */) {
      line += 1;
      lineStart = i + 1;
    }
  }
  return { line, column: offset - lineStart + 1 };
}

/**
 * Offsets at which injecting a single '#' yields a first-error location exactly
 * equal to that offset: outside any string literal, and not immediately
 * following a value-token character. Always includes offset 0.
 */
function safeInjectionOffsets(text: string): number[] {
  const offsets: number[] = [];
  let inString = false;
  let escaped = false;

  for (let i = 0; i <= text.length; i++) {
    const insideString = inString;
    const prevIsValueChar = i > 0 && VALUE_TOKEN_CHAR.test(text[i - 1]);
    if (!insideString && !prevIsValueChar) {
      offsets.push(i);
    }

    if (i < text.length) {
      const ch = text[i];
      if (inString) {
        if (escaped) escaped = false;
        else if (ch === '\\') escaped = true;
        else if (ch === '"') inString = false;
      } else if (ch === '"') {
        inString = true;
      }
    }
  }

  return offsets;
}

// ─── Renderers: compact + every multi-line indentation style ─────────────────

const INDENT_STYLES: IndentStyle[] = [
  { kind: 'space', size: 2 },
  { kind: 'space', size: 4 },
  { kind: 'tab' },
];

/** A renderer turning a model into valid JSON text. */
const rendererArbitrary = fc.constantFrom(
  ...[
    serialize,
    ...INDENT_STYLES.map((style) => (model: Parameters<typeof serialize>[0]) =>
      format(model, style),
    ),
  ],
);

// ─── Property ─────────────────────────────────────────────────────────────────

describe('Property 14: Validator reports the first error at the correct 1-based position (Req 6.4)', () => {
  test.prop(
    [jsonArbitrary(), rendererArbitrary, fc.double({ min: 0, max: 1, noNaN: true })],
    { numRuns: 100 },
  )(
    'reports the injected first error at its computed 1-based line/column',
    (model, render, selector) => {
      const validText = render(model);

      // Guard: the undeformed document must itself be valid, otherwise the
      // injection would be meaningless (a vacuous pass).
      const baseline = parseJson(validText);
      expect(baseline.ok).toBe(true);

      // Choose a deterministic safe injection site from the generated selector.
      const sites = safeInjectionOffsets(validText);
      const offset = sites[Math.min(sites.length - 1, Math.floor(selector * sites.length))];

      const injected = validText.slice(0, offset) + INJECTED + validText.slice(offset);
      const expected = lineColumn(injected, offset);

      const result = parseJson(injected);
      if (result.ok) {
        throw new Error(
          `expected a syntax error after injecting '#' at offset ${offset}, but parse succeeded`,
        );
      }

      // The error type must be identified (non-empty), and the location must be
      // the 1-based line/column of the injected character.
      expect(result.error.type.length).toBeGreaterThan(0);
      if (result.error.line !== expected.line || result.error.column !== expected.column) {
        throw new Error(
          `offset ${offset}: expected (line ${expected.line}, column ${expected.column}) ` +
            `but got (line ${result.error.line}, column ${result.error.column}); ` +
            `text=${JSON.stringify(injected)}`,
        );
      }
      return true;
    },
  );

  // ─── Example-based checks for concrete, human-readable cases ───────────────

  it('locates an error on the first line', () => {
    const result = parseJson('{ "a": @ }');
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.line).toBe(1);
      expect(result.error.column).toBe(8);
      expect(result.error.type.length).toBeGreaterThan(0);
    }
  });

  it('locates an error on a later line with the correct column', () => {
    const text = '{\n  "a": 1,\n  "b": :\n}';
    // Line 3 is `  "b": :` — the stray ':' (where a value is expected) sits at
    // column 8 (1-based).
    const result = parseJson(text);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.line).toBe(3);
      expect(result.error.column).toBe(8);
    }
  });

  it('treats empty/whitespace-only input as valid (no error reported)', () => {
    expect(parseJson('').ok).toBe(true);
    expect(parseJson('   \n\t ').ok).toBe(true);
  });
});
